### ISSUE TITLE
landscape rotation bug with python2-pillow 3.0.0

### ISSUE THREAD

**Issue by tYYGH** [jflesch/paperwork#398]
With python2-pillow 2.9.0, a portrait-scanned landscape-page is correctly rotated (even though it insists on being upside-down for some reason…).

With python2-pillow 3.0.0, a portrait-scanned landscape-page is correctly handled up to the point where the four miniatures are displayed (each of the four possible orientations).
And then the selected orientation is displayed full-page. It is the correct one (except for the upside-down thing). BUT the full-page being displayed is actually a portrait page, with the right and left sides of the picture being clipped, and thick black borders being added at the top and bottom.

**Comment by jflesch** [comment]
Can you tell me which GNU/Linux distribution do you use please ?

If you run Paperwork from a terminal, is there any Python exception appearing somewhere in the output ?

Optional : Also, I think some screenshots could help. Can you make some please ?

**Comment by tYYGH** [comment]
Sorry, I should have done just that right away. I’m using Arch Linux. Paperwork is from Git (not a distribution package) in a virtualenv. Pillow is a package, however.
I diff’ed a normal run (pillow 0.2.9) and an abnormal one (pillow 3.0.0), and the difference is this:
```
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```
Full log: http://yalis.fr/public/www/pw%2bpillow300.log
Screenshots with Pillow 2.9.0:
— thumbnails: http://yalis.fr/public/www/pw%2bpillow290_4pic.jpg
— full page: http://yalis.fr/public/www/pw%2bpillow290_full.jpg
Screenshots with Pillow 2.9.0:
— thumbnails: http://yalis.fr/public/www/pw%2bpillow300_4pic.jpg
— full page: http://yalis.fr/public/www/pw%2bpillow300_full.jpg

**Comment by jflesch** [comment]
Got it : https://github.com/python-pillow/Pillow/issues/1500

**Comment by jflesch** [comment]
I've pushed fixes on the branch 'stable' and 'unstable'. Can you try them please ?

**Comment by jflesch** [comment]
Ok, I've tested with Pillow 3.0 + branch 'unstable': I can reproduce the problem, and my changes do fix this problem.

Please reopen if you still have problems with page rotation.

**Comment by tYYGH** [comment]
Bug is still there in “stable”. Would “unstable” be mostly ok for daily usage?

**Comment by jflesch** [comment]
I use it for daily usage.
But still, it's considered 'unstable' as I haven't tested all the features yet (and some may be still missing).
